# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LUGFI
#email: your-email@domain.com
description: > # this means to ignore newlines until "image:"
  LUGFI usa GNU/Linux en la Facultad de Ingeniería de la UBA.
image: "/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lugfi.github.com" # the base hostname & protocol for your site
github_username: lugfi

# Build settings
#markdown: kramdown ·# Default is 'kramdown'.

gems:
  - jekyll-mentions
